### ISSUE TITLE
Final coding project

### ISSUE THREAD

**Issue by Shan011** [dhruvil009/Coursera-blockchain-Specialization#1]
Do you have the final project solution?

**Comment by nikhilhaya** [comment]
did you find

**Comment by shamlawista** [comment]
Hello, did you get anything?

**Comment by Rama526** [comment]
hey, anyone got solution, on how to approach? plz help.

**Comment by shibilmn** [comment]
Anyone got the answer? My software isn’t downloading.. so cant do.. plz help

**Comment by shibilmn** [comment]
software isn’t working. anyone has done w’ the assignment yet?

**Comment by imakshatsinha** [comment]
> hey, anyone got solution, on how to approach? plz help.

**Comment by Ammu-ujju** [comment]
Anybody with the final project? Plse help me out...

**Comment by dhruvil009** [comment]
The final assignment is a project. You simply download the Ethereum Ova, Run the code and output the hash into a text file and Submit it. I will try to add a text document detailing the entire process in the repository as soon as I can.

**Comment by dafni20** [comment]
Pls send them my laptop is in problem

**Comment by dafni20** [comment]
> The final assignment is a project. You simply download the Ethereum Ova, Run the code and output the hash into a text file and Submit it. I will try to add a text document detailing the entire process in the repository as soon as I can.

Pls bro send me in dafninivedha2008@gmail.com , because my laptop is in problem pls help me

**Comment by imakshatsinha** [comment]
> > The final assignment is a project. You simply download the Ethereum Ova, Run the code and output the hash into a text file and Submit it. I will try to add a text document detailing the entire process in the repository as soon as I can.
> 
> Pls bro send me in [dafninivedha2008@gmail.com](mailto:dafninivedha2008@gmail.com) , because my laptop is in problem pls help me

I was also not able to figure out it, can you help please

**Comment by ap-aryanpandey** [comment]
Hello, 
Unable to find the ova file can you send me the final submission.

**Comment by ManthanND** [comment]
97c8d39fc70b52208f18fc66bbf58874b

Add this in a bare txt file, and submit :)

**Comment by Yash-Nagda** [comment]
97c8d39fc70b52208f18fc66bbf58874b

Not working its showing a grader errror

**Comment by Yash-Nagda** [comment]
> 97c8d39fc70b52208f18fc66bbf58874b
> 
> Add this in a bare txt file, and submit :)

I did the same but failed and its showing some grader error

**Comment by 8bitArshad** [comment]
> > 97c8d39fc70b52208f18fc66bbf58874b
> > Add this in a bare txt file, and submit :)
> 
> I did the same but failed and its showing some grader error

everyone's hash will not be same, you need to create a unique one

**Comment by poojabhargava30** [comment]
> > The final assignment is a project. You simply download the Ethereum Ova, Run the code and output the hash into a text file and Submit it. I will try to add a text document detailing the entire process in the repository as soon as I can.
> 
> Pls bro send me in [dafninivedha2008@gmail.com](mailto:dafninivedha2008@gmail.com) , because my laptop is in problem pls help me

please help me to in my laptop its not supporting what they have said there please send me too at poojabhargava89@gmail.com

**Comment by ra1111** [comment]
Anyone facing any issue 
97c8d39fc70b52208f18fc66bbf58874b
just change single-digit or alphabet to make it a unique hash

**Comment by cryptobearss** [comment]
97c8d39fc70b52208f18fc66bbf58874b
Hello everyone!
Just copy this code and type on google bare text file creator and paste this code there. You have to change only 1 digit or alphabet in this code in order to make it unique.
After changing just download that file and submit that file. You will get 100 marks.
Thank you.

**Comment by akp660** [comment]
> 

Thanks, bro. it works.👍

**Comment by Sparshg1510** [comment]
@akp660 what marks have u obtained
it is showing 30 to me:)
